// client/components/header/Profile.vue
<template>
	<div class="absolute top-9 right-9">
		<GenDropdownMenu>
			<GenDropdownMenuTrigger>
				<div v-if="!isLoading" class="flex items-center">
					<div class="text-right mr-3">
						<p class="font-bold -mb-1">
							{{ data?.user.nickname }}
						</p>
						<div v-if="data?.user.firstName" class="flex justify-between">
							<p v-if="data?.user.firstName" class="text-sm opacity-40">
								{{ data?.user.firstName }}
							</p>
							<p v-if="data?.user.lastName" class="text-sm opacity-40">
								{{ data?.user.lastName }}
							</p>
						</div>
						<p class="text-sm opacity-40">
							{{ data?.user.email }}
						</p>
					</div>

					<div
						class="w-10 h-10 flex justify-center items-center text-2xl text-foreground bg-white/20 rounded uppercase border border-primary"
					>
						{{
							data?.user.nickname?.charAt(0) ||
							data?.user.firstName?.charAt(0) ||
							data?.user.email.charAt(0)
						}}
					</div>
				</div>
			</GenDropdownMenuTrigger>
			<GenDropdownMenuContent class="w-56">
				<GenDropdownMenuItem>
					<Settings class="mr-2 h-4 w-4" />
					<NuxtLink to="/app/settings">Settings</NuxtLink>
					<GenDropdownMenuShortcut>⌘S</GenDropdownMenuShortcut>
				</GenDropdownMenuItem>
				<GenDropdownMenuSeparator />
				<GenDropdownMenuItem @click="mutate()">
					<LogOut class="mr-2 h-4 w-4" />
					<span>Log out</span>
					<GenDropdownMenuShortcut>⇧⌘Q</GenDropdownMenuShortcut>
				</GenDropdownMenuItem>
			</GenDropdownMenuContent>
		</GenDropdownMenu>
	</div>
</template>

<script setup lang="ts">
import { LogOut, Settings } from 'lucide-vue-next'

const { $api } = useNuxtApp()
const { push } = useRouter()

const { data, isLoading } = useQuery({
	queryKey: ['profile'],
	queryFn: () => $api.user.getProfile(),
})

const { mutate } = useMutation({
	mutationKey: ['logout'],
	mutationFn: () => $api.auth.logout(),
	onSuccess: () => {
		push('/auth')
	},
})
</script>

// client/components/profile.tsx
"use client"

import {
	DropdownMenu,
	DropdownMenuTrigger
} from "@radix-ui/react-dropdown-menu"
import { useMutation } from "@tanstack/react-query"
import { LogOut, Settings } from "lucide-react"
import { useRouter } from "next/navigation"

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import {
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuLabel,
	DropdownMenuSeparator,
	DropdownMenuShortcut
} from "@/components/ui/dropdown-menu"

import { useProfile } from "@/hooks/useProfile"

import api from "@/api"

export function Profile() {
	const router = useRouter()

	const { data, isLoading } = useProfile()

	const { mutate } = useMutation({
		mutationKey: ["logout"],
		mutationFn: () => api.auth.logout(),
		onSuccess: () => router.push("/sign-in")
	})

	return (
		<div>
			<div className="flex items-center">
				<DropdownMenu>
					<DropdownMenuTrigger asChild>
						<Avatar className="cursor-pointer">
							<AvatarImage src="/default" />
							<AvatarFallback className="bg-violet-500 hover:bg-violet-900 transition-colors text-white font-medium text-xl capitalize">
								{data?.user.nickname?.charAt(0) ||
									data?.user.firstName?.charAt(0) ||
									data?.user.email.charAt(0)}
							</AvatarFallback>
						</Avatar>
					</DropdownMenuTrigger>
					<DropdownMenuContent className="w-56">
						<DropdownMenuLabel className="text-ellipsis overflow-hidden">
							{data?.user.nickname
								? data?.user.firstName && data?.user.lastName
									? `${data.user.nickname} (${data.user.firstName} ${data.user.lastName})`
									: `${data.user.nickname}`
								: data?.user.email}
						</DropdownMenuLabel>
						<DropdownMenuSeparator />
						<DropdownMenuItem onClick={() => router.push("/app/settings")}>
							<Settings className="mr-2 h-4 w-4" />
							<span>Settings</span>
							<DropdownMenuShortcut>⌘S</DropdownMenuShortcut>
						</DropdownMenuItem>
						<DropdownMenuSeparator />
						<DropdownMenuItem onClick={() => mutate()}>
							<LogOut className="mr-2 h-4 w-4" />
							<span>Log out</span>
							<DropdownMenuShortcut>⇧⌘Q</DropdownMenuShortcut>
						</DropdownMenuItem>
					</DropdownMenuContent>
				</DropdownMenu>
			</div>
		</div>
	)
}
