// client/components/settings.tsx
import { useAutoAnimate } from "@formkit/auto-animate/react"
import { zodResolver } from "@hookform/resolvers/zod"
import { SubmitHandler, useForm } from "react-hook-form"

import { TypeUserForm } from "@/types/user.types"

import { useInitialSettings } from "@/hooks/useInitialSettings"
import { useUpdateSettings } from "@/hooks/useUpdateSettings"

import { Button } from "./ui/button"
import {
	Form,
	FormControl,
	FormField,
	FormItem,
	FormLabel,
	FormMessage
} from "./ui/form"
import { Input } from "./ui/input"
import api from "@/api"

export function Settings() {
	const [parent] = useAutoAnimate()

	const form = useForm<TypeUserForm>({
		mode: "onChange",
		resolver: zodResolver(api.user.settingsValidationSchema)
	})

	useInitialSettings(form.reset)
	const { mutate, isPending } = useUpdateSettings()

	const onSubmit: SubmitHandler<TypeUserForm> = data => {
		const { password, ...rest } = data

		mutate({
			...rest,
			password: data.password || undefined
		})
	}

	return (
		<Form {...form}>
			<form onSubmit={form.handleSubmit(onSubmit)}>
				<div className="grid grid-cols-2 gap-10">
					<div className="flex flex-col gap-y-2">
						<FormField
							control={form.control}
							name="email"
							render={({ field }) => (
								<FormItem ref={parent}>
									<FormLabel className="font-medium">Email</FormLabel>
									<FormControl>
										<Input
											className="w-full rounded-xl p-4 bg-transparent"
											type="email"
											placeholder="Email"
											{...field}
										/>
									</FormControl>
									<FormMessage />
								</FormItem>
							)}
						/>
						<FormField
							control={form.control}
							name="nickname"
							render={({ field }) => (
								<FormItem ref={parent}>
									<FormLabel className="font-medium">Nickname</FormLabel>
									<FormControl>
										<Input
											className="w-full rounded-xl p-4 bg-transparent"
											type="text"
											placeholder="Nickname"
											{...field}
										/>
									</FormControl>
									<FormMessage />
								</FormItem>
							)}
						/>
						<FormField
							control={form.control}
							name="firstName"
							render={({ field }) => (
								<FormItem ref={parent}>
									<FormLabel className="font-medium">First Name</FormLabel>
									<FormControl>
										<Input
											className="w-full rounded-xl p-4 bg-transparent"
											type="text"
											placeholder="First Name"
											{...field}
										/>
									</FormControl>
									<FormMessage />
								</FormItem>
							)}
						/>
						<FormField
							control={form.control}
							name="lastName"
							render={({ field }) => (
								<FormItem ref={parent}>
									<FormLabel className="font-medium">Last Name</FormLabel>
									<FormControl>
										<Input
											className="w-full rounded-xl p-4 bg-transparent"
											type="text"
											placeholder="Last Name"
											{...field}
										/>
									</FormControl>
									<FormMessage />
								</FormItem>
							)}
						/>
						<FormField
							control={form.control}
							name="password"
							render={({ field }) => (
								<FormItem ref={parent}>
									<FormLabel className="font-medium">Password</FormLabel>
									<FormControl>
										<Input
											className="w-full rounded-xl p-4 bg-transparent"
											type="text"
											placeholder="Password"
											{...field}
										/>
									</FormControl>
									<FormMessage />
								</FormItem>
							)}
						/>
					</div>
					<div>
						<FormField
							control={form.control}
							name="workInterval"
							render={({ field }) => (
								<FormItem ref={parent}>
									<FormLabel className="font-medium">
										Work Interval (min.)
									</FormLabel>
									<FormControl>
										<Input
											className="w-full rounded-xl p-4 bg-transparent"
											type="number"
											placeholder="Work Interval (min.)"
											{...field}
											onChange={e => {
												if (e.target.value === "")
													return field.onChange(undefined)
												field.onChange(Number(e.target.value))
											}}
										/>
									</FormControl>
									<FormMessage />
								</FormItem>
							)}
						/>
						<FormField
							control={form.control}
							name="breakInterval"
							render={({ field }) => (
								<FormItem ref={parent}>
									<FormLabel className="font-medium">
										Break Interval (min.)
									</FormLabel>
									<FormControl>
										<Input
											className="w-full rounded-xl p-4 bg-transparent"
											type="number"
											placeholder="Break Interval (min.)"
											{...field}
											onChange={e => {
												if (e.target.value === "")
													return field.onChange(undefined)
												field.onChange(Number(e.target.value))
											}}
										/>
									</FormControl>
									<FormMessage />
								</FormItem>
							)}
						/>
						<FormField
							control={form.control}
							name="intervalsCount"
							render={({ field }) => (
								<FormItem ref={parent}>
									<FormLabel className="font-medium">
										Intervals Count (max 10)
									</FormLabel>
									<FormControl>
										<Input
											className="w-full rounded-xl p-4 bg-transparent"
											type="number"
											placeholder="Intervals Count (max 10)"
											{...field}
											onChange={e => {
												if (e.target.value === "")
													return field.onChange(undefined)
												field.onChange(Number(e.target.value))
											}}
										/>
									</FormControl>
									<FormMessage />
								</FormItem>
							)}
						/>
					</div>
				</div>

				<Button
					type="submit"
					disabled={isPending}
					variant="primary"
					size="sm"
					className="mt-8 w-full"
				>
					Save
				</Button>
			</form>
		</Form>
	)
}

// client/pages/app/settings.vue
<template>
	<div>
		<UiHeading title="Settings" />
		<div>
			<form @submit="onSubmit" class="form">
				<div class="grid grid-cols-2 gap-10">
					<div class="flex flex-col gap-y-8">
						<GenFormField v-slot="{ componentField }" name="email">
							<GenFormItem v-auto-animate>
								<GenFormLabel class="text-base">Email</GenFormLabel>
								<GenFormControl>
									<GenInput
										type="email"
										placeholder="Email"
										v-bind="componentField"
									/>
								</GenFormControl>
								<GenFormMessage />
							</GenFormItem>
						</GenFormField>

						<GenFormField v-slot="{ componentField }" name="nickname">
							<GenFormItem v-auto-animate>
								<GenFormLabel class="text-base">Nickname</GenFormLabel>
								<GenFormControl>
									<GenInput
										type="text"
										placeholder="Nickname"
										v-bind="componentField"
									/>
								</GenFormControl>
								<GenFormMessage />
							</GenFormItem>
						</GenFormField>

						<GenFormField v-slot="{ componentField }" name="firstName">
							<GenFormItem v-auto-animate>
								<GenFormLabel class="text-base">First name</GenFormLabel>
								<GenFormControl>
									<GenInput
										type="text"
										placeholder="First name"
										v-bind="componentField"
									/>
								</GenFormControl>
								<GenFormMessage />
							</GenFormItem>
						</GenFormField>

						<GenFormField v-slot="{ componentField }" name="lastName">
							<GenFormItem v-auto-animate>
								<GenFormLabel class="text-base">Last name</GenFormLabel>
								<GenFormControl>
									<GenInput
										type="text"
										placeholder="Last name"
										v-bind="componentField"
									/>
								</GenFormControl>
								<GenFormMessage />
							</GenFormItem>
						</GenFormField>

						<GenFormField v-slot="{ componentField }" name="password">
							<GenFormItem v-auto-animate>
								<GenFormLabel class="text-base">Password</GenFormLabel>
								<GenFormControl>
									<GenInput
										type="password"
										placeholder="Password"
										v-bind="componentField"
									/>
								</GenFormControl>
								<GenFormMessage />
							</GenFormItem>
						</GenFormField>
					</div>

					<div class="flex flex-col gap-y-8">
						<GenFormField v-slot="{ componentField }" name="workInterval">
							<GenFormItem v-auto-animate>
								<GenFormLabel class="text-base"
									>Work interval (min)</GenFormLabel
								>
								<GenFormControl>
									<GenInput
										type="number"
										placeholder="Work interval (min)"
										v-bind="componentField"
									/>
								</GenFormControl>
								<GenFormMessage />
							</GenFormItem>
						</GenFormField>

						<GenFormField v-slot="{ componentField }" name="breakInterval">
							<GenFormItem v-auto-animate>
								<GenFormLabel class="text-base"
									>Break interval (min)</GenFormLabel
								>
								<GenFormControl>
									<GenInput
										type="number"
										placeholder="Break interval (min)"
										v-bind="componentField"
									/>
								</GenFormControl>
								<GenFormMessage />
							</GenFormItem>
						</GenFormField>

						<GenFormField v-slot="{ componentField }" name="intervalsCount">
							<GenFormItem v-auto-animate>
								<GenFormLabel class="text-base"
									>Intervals count (max 10)</GenFormLabel
								>
								<GenFormControl>
									<GenInput
										type="number"
										placeholder="Intervals count (max 10)"
										v-bind="componentField"
									/>
								</GenFormControl>
								<GenFormMessage />
							</GenFormItem>
						</GenFormField>
					</div>
				</div>

				<GenButton
					class="mt-5"
					type="submit"
					:disabled="isPending"
					variant="outline"
					>Save</GenButton
				>
			</form>
		</div>
	</div>
</template>

<script setup lang="ts">
definePageMeta({
	middleware: 'auth',
})

import { vAutoAnimate } from '@formkit/auto-animate/vue'
import { toTypedSchema } from '@vee-validate/valibot'
import { useForm } from 'vee-validate'
import { toast } from 'vue-sonner'
import type { TypeUserForm } from '~/types/user.types'

const { $api } = useNuxtApp()
const queryClient = useQueryClient()
const { handleSubmit, resetForm } = useForm<TypeUserForm>({
	validationSchema: toTypedSchema($api.user.settingsValidationSchema),
})

const { data: queryData, isSuccess } = useQuery({
	queryKey: ['profile'],
	queryFn: () => $api.user.getProfile(),
})

const { mutate, isPending } = useMutation({
	mutationKey: ['update profile'],
	mutationFn: (data: TypeUserForm) => $api.user.update(data),
	onSuccess(data) {
		toast.success('Successfully update profile!')
		queryClient.invalidateQueries({ queryKey: ['profile'] })
		resetForm({
			values: {
				email: data.email,
				firstName: data.firstName,
				lastName: data.lastName,
				nickname: data.nickname,
				breakInterval: data.breakInterval,
				intervalsCount: data.intervalsCount,
				workInterval: data.workInterval,
			},
		})
	},
})

const onSubmit = handleSubmit(data => {
	const { password, ...rest } = data

	mutate({
		...rest,
		password: password || undefined,
	})
})

watch(
	isSuccess,
	() => {
		if (isSuccess.value === true && queryData) {
			resetForm({
				values: {
					email: queryData.value?.user.email,
					firstName: queryData.value?.user.firstName,
					lastName: queryData.value?.user.lastName,
					nickname: queryData.value?.user.nickname,
					breakInterval: queryData.value?.user.breakInterval,
					intervalsCount: queryData.value?.user.intervalsCount,
					workInterval: queryData.value?.user.workInterval,
				},
			})
		}
	},
	{
		immediate: true,
	}
)
</script>
